# --- !Ups

create table "events" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null
);

create table "event_dates" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "event" bigint not null,
  "date" varchar not null,

  foreign key ("event") references "events" ("id")
);

create table "votes" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "event_date" bigint not null,
  "voter" varchar not null,

  foreign key ("event_date") references "event_dates" ("id")
);

create view "all_voters_per_event" as (
  select distinct e.id as event, v.voter as voter
  from events e
    join event_dates ed on e.id = ed.event
    join votes v on ed.id = v.event_date
);

create view "voters_per_event_date" as (
  select distinct ed.id as event_date, v.voter as voter
  from event_dates ed
    join votes v on ed.id = v.event_date
);

# --- !Downs

drop view "all_voters_per_event" if exists;
drop view "voters_per_event_date" if exists;
drop table "votes" if exists;
drop table "event_dates" if exists;
drop table "events" if exists;
